[package]
name = "chap2_elliptic_curve"
version = "0.1.0"
authors = ["nillnull <nilnu1l@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
