[package]
name = "chap1_fieldElement"
version = "0.1.0"
authors = ["nillnull <nilnu1l@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
module = "0.1.0"
modulo = "0.1.2"
num-traits = "0.2.14"
